# File: .github/workflows/ci.yml
name: Python CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main   # or the branch you want PRs to target
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # choose the version you want

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4️⃣ Run tests
      - name: Run unit tests
        run: |
          pip install -r requirements.txt
          pip install -e .
          pytest tests/
